name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Dubna
      run: >-
        git clone https://github.com/besm6/dubna.git &&
        make -C dubna install

    - name: Pascompl
      run: >-
        git clone https://github.com/besm6/pascal-re.git &&
        make -C pascal-re pascompl &&
        install -v pascal-re/pascompl /usr/local/bin/pascompl

    - name: Build
      run: make

    - name: Install besmc
      run: sudo install -v build/besmc /usr/local/bin/besmc

    - name: C compiler
      run: >-
        git clone https://github.com/besm6/c-compiler.git &&
        make -C c-compiler &&
        cmake --install c-compiler/build --prefix $HOME/.local

    - name: Run tests
      run: make test
