name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Dubna
      run: >-
        git clone https://github.com/besm6/dubna.git &&
        make -C dubna install
    - name: Pascompl
      run: >-
        git clone https://github.com/besm6/pascal-re.git &&
        make -C pascal-re pascompl &&
        install -v pascal-re/pascompl /usr/local/bin/pascompl
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose -- --test-threads=1
